project_name: mzap

before:
  hooks:
  - go mod download

builds:
  -
    main: .
    binary: mzap
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
    - '^MERGE'
    - "{{ .Tag }}"

release:
  github:
    owner: hahwul
    name: mzap

brews:
  -
    name: mzap
    tap:
      owner: hahwul
      name: homebrew-mzap
    url_template: "https://github.com/hahwul/mzap/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: hahwul
      email: hahwul@gmail.com
    folder: Formula
    homepage: "https://www.hahwul.com"
    description: "Multiple target ZAP scanning / mzap is a tool for scanning N*N in ZAP."
    test: |
      system "#{bin}/mzap version"
    install: |
      bin.install "mzap"
snapcrafts:
  -
    name: mzap
    # Remember you need to `snapcraft login` first.
    publish: true
    summary: Multiple target ZAP scanning
    description: Multiple target ZAP scanning / mzap is a tool for scanning N*N in ZAP.
    grade: stable
    confinement: strict
    license: MIT
    apps:
      mzap:
        plugs: ["home","network"]
